version: '3.1'
services:

  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - "80:80" # Port HTTP
      - "443:443" # Port HTTPS
      - "443:443/udp" # Port HTTPS
    volumes:
      - /etc/caddy/:/etc/caddy/ # No tocar. Ruta on hi haurà la configuració de Caddy
      - caddy_data:/data # No tocar. Volum per a que funcioni Caddy
      - caddy_config:/config # No tocar. Volum per a que funcioni Caddy

volumes:
  caddy_data: # Caddy Volume
  caddy_config: # Caddy Volume
