version: '3.1'

services:
  headscale-database:
    container_name: headscale-database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: headscale-password
      POSTGRES_DB: headscale
      POSTGRES_USER: headscale
    ports:
      - "8081:5432"
    volumes:
      - /etc/headscale-database:/var/lib/postgresql/data
