version: '3.1'

  headscale:
    image: headscale/headscale:0.23.0-alpha2 # No tocar. Versio que funciona amb la configuracio.
    container_name: headscale
    restart: always
    volumes:
      - /etc/headscale/:/etc/headscale/ # No tocar. Ruta on hi haurà la configuració de Headscale.
    command: headscale serve # No tocar. Comando que executara el contenidor quant s'obri.

  headscale-database:
    container_name: headscale-database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: # Afegir contrasenya de Postgres.
      POSTGRES_DB: headscale # No tocar. Base de dades utilitzada a Postgres.
      POSTGRES_USER: headscale # No tocar. Usuari de Postgres.
    volumes:
      - /etc/headscale-database:/var/lib/postgresql/data # No tocar. Ruta on hi haurà la base da dades.
