version: '3.1'

services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 11180:80
    environment:
      WORDPRESS_DB_HOST: wordpress-database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress-password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /etc/wordpress:/var/www/html

  wordpress-database:
    container_name: wordpress-database
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress-password
      MYSQL_ROOT_PASSWORD: wordpress-root
    volumes:
      - /etc/wordpress-database:/var/lib/mysql

  wordpress-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress-phpmyadmin
    restart: always
    ports:
      - 11181:80
    environment:
      MYSQL_ROOT_PASSWORD: wordpress-root
