version: '3.7' # A common Compose file version 

services:
  nginxproxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxy  # Optional, but good for management
    restart: unless-stopped     # Keep container running unless manually stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /etc/nginx/data:/data 
      - /etc/nginx/letsencrypt:/etc/letsencrypt 
