version: '3.7'

services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxymanager
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /etc/nginxproxymanager/data:/data
      - /etc/nginxproxymanager/letsencrypt:/etc/letsencrypt
