version: '3.7'

services:
  portainerce:
    container_name: portainerce
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9443:9443 # Port HTTP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # No tocar. Nessesari perque Portainer tingu acces als contenidos de Docker
      - portainer_data:/data # No tocar. Volum on es guardara la configuracio de Portainer

volumes:
  portainer_data:
